// Certificado PÚBLICO de QZ Tray (CN=PideLoNuestro, vence 2036-09-22).
// No es secreto: es el mismo que se instala como override.crt en la PC del restaurante.
// Vive en el código para no depender de pegarlo a mano en variables de entorno.
// La clave privada que lo acompaña va SOLO en QZ_PRIVATE_KEY_BASE64 (servidor).
export const QZ_CERTIFICATE = `-----BEGIN CERTIFICATE-----
MIIDETCCAfmgAwIBAgIUK5ZNfCkIz5F9U8cn45oCtbF4RrEwDQYJKoZIhvcNAQEL
BQAwGDEWMBQGA1UEAwwNUGlkZUxvTnVlc3RybzAeFw0yNjA5MjUyMDEzNDFaFw0z
NjA5MjIyMDEzNDFaMBgxFjAUBgNVBAMMDVBpZGVMb051ZXN0cm8wggEiMA0GCSqG
SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDksEqWmZ2MYv1C39vKuDdRWogtvbbxIKe7
WSCvdBOm8Vpzu/D9fZ3NL1S0jDeONgsD6dnhJBeJUi96rItCD47tINmDF8afxyai
xzqM0UWeeEJzwjROP1LVaGOL2RVz7p+7iR0LM6InHDEhWkyiBYz4FKMGWj4t5Sdk
sirteN+ieiNgzj/hQUYc994YhahI8SQx9dR7ezbjtxld0U/dPFWSSxbron1pEAyF
y/gprj6fwPI9CFZ6oTJwfDgzbu0OV1NuF2liW4yzxrUgvQ6zSDBP9FlgZZErDzmT
dl2dWVYFxoUL2348mOLOlIQUQMwuoG/F+F1yHE4Ss3M0JJRTn0IfAgMBAAGjUzBR
MB0GA1UdDgQWBBSRS7n+wNLCGvE3NS5lpeCdgKWvYzAfBgNVHSMEGDAWgBSRS7n+
wNLCGvE3NS5lpeCdgKWvYzAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
A4IBAQCbHLZpZWogfkMgdqFBRUdabPva5ulS/Yorpr3Zgabtg64COLoHYkujtSNT
Yuutdz4v2OQ3Pihqby2++3ftBeljhSdEdbF6hYHdrb3+FwWhGfNtDc8bOaX8GlgA
8FJLYnhtG+t8w7X0z+aEcUKea0iwomZE/T5MS8YZmiZeMOnmmRQBHDXMSRNiBimd
HFyjk9VaYKlfryuR5BR3jrU8nyFO9b1YVCPJ41rqWkduumtncS9NXCHBQx6n/5R4
/uEdNCgMkouucd1CyKFJvTKf2OSpa0pIGNAdWEGEaTvdSp47miZNksjHe9BoQpD6
+QAs4VGSsOdsVS6qqL6Ji90co8gw
-----END CERTIFICATE-----`;
